# Generated by Django 3.2.9 on 2023-05-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_reviews_date_reviews_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='author',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='number_of_page',
        ),
        migrations.AddField(
            model_name='product',
            name='Size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=100, null=True),
        ),
    ]
